# Generated by Django 5.1.4 on 2025-01-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LFT', '0003_remove_lostitem_category_message_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='STATUS_CHOICES', max_length=20),
        ),
    ]
