# Generated by Django 5.1.4 on 2025-01-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LFT', '0004_alter_lostitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='status',
        ),
    ]
